In [2]:
import pandas as pd
data = pd.read_csv('./data/FIFA_data.csv')

In [3]:
#data.sort_values('Age') - 선수들의 나이 분포 확인 (16 ~ 45세)
#data.groupby('Age').count() - 어떤 나이대에 가장 많이 분포되어 있는지
data.sort_values('Overall', ascending = False).head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
11422,237160,R. Williams,19,England,150.0,79.0,Manchester United,€875K,€8K,Right,...,51.0,63.0,68.0,66.0,7.0,5.0,6.0,6.0,9.0,€2.2M
0,158023,L. Messi,31,Argentina,94.0,94.0,FC Barcelona,€110.5M,€565K,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,Portugal,94.0,94.0,Juventus,€77M,€405K,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,Brazil,92.0,93.0,Paris Saint-Germain,€118.5M,€290K,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,Spain,91.0,93.0,Manchester United,€72M,€260K,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,Belgium,91.0,92.0,Manchester City,€102M,€355K,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,183277,E. Hazard,27,Belgium,91.0,91.0,Chelsea,€93M,€340K,Right,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,177003,L. Modrić,32,Croatia,91.0,91.0,Real Madrid,€67M,€420K,Right,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,176580,L. Suárez,31,Uruguay,91.0,91.0,FC Barcelona,€80M,€455K,Right,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,155862,Sergio Ramos,32,Spain,91.0,91.0,Real Madrid,€51M,€380K,Right,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M

# 1. 최고 유망주 3명

포지션별 3명씩 뽑아보기
1. gk_list = ['GK']
2. cb_list = ['CB', 'LCB', 'RCB', 'RB', 'LB']
3. mf_list = ['RCM', 'LCM', 'RDM', 'CDM', 'CM','RM', 'CAM']
4. st_list = ['ST', 'LW', 'RW']

유망주의 기준 - 나이 : 16~20세

선수 가치 - 오버롤 * 1/3 + 포텐셜 * 2/3 

: 포텐셜에 더 중점을 두고 계산.

In [4]:
# 20세 이하 선수들만 뽑기.
hope = data[data['Age'] <= 20]
#hope.info() 
hope.head()
#총 3327명

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
25,231747,K. Mbappé,19,France,88.0,95.0,Paris Saint-Germain,€81M,€100K,Right,...,86.0,34.0,34.0,32.0,13.0,5.0,7.0,11.0,6.0,€166.1M
226,235243,M. de Ligt,18,Netherlands,82.0,91.0,Ajax,€27M,€11K,Right,...,77.0,84.0,84.0,79.0,12.0,11.0,11.0,12.0,10.0,€43.2M
229,230621,G. Donnarumma,19,Italy,82.0,93.0,Milan,€29M,€23K,Right,...,68.0,20.0,14.0,16.0,88.0,78.0,72.0,78.0,88.0,€55.1M
319,231677,M. Rashford,20,England,81.0,89.0,Manchester United,€27M,€110K,Right,...,73.0,32.0,40.0,33.0,11.0,6.0,15.0,7.0,14.0,€55.4M
321,229906,L. Bailey,20,Jamaica,81.0,89.0,Bayer 04 Leverkusen,€26.5M,€54K,Left,...,75.0,45.0,27.0,18.0,12.0,13.0,6.0,15.0,14.0,€50.4M

In [5]:
#오버롤과 포텐셜을 이용한 새로운 컬럼 만들기
pd.set_option('display.max_columns', 80)
hope['OP'] = (hope['Overall'] * 1/3) + (hope['Potential'] * 2/3)
hope.head()

<ipython-input-5-c427299915e3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hope['OP'] = (hope['Overall'] * 1/3) + (hope['Potential'] * 2/3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Position,Jersey Number,Joined,Contract Valid Until,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,...,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,OP
25,231747,K. Mbappé,19,France,88.0,95.0,Paris Saint-Germain,€81M,€100K,Right,3.0,4.0,5.0,RM,10.0,"Jul 1, 2018",2022,5'10,161lbs,85+3,85+3,85+3,87+3,87+3,87+3,87+3,87+3,86+3,86+3,86+3,86+3,78+3,78+3,78+3,86+3,66+3,62+3,62+3,62+3,66+3,...,54+3,54+3,54+3,62+3,77.0,88.0,77.0,82.0,78.0,90.0,77.0,63.0,73.0,91.0,96.0,96.0,92.0,87.0,83.0,79.0,75.0,83.0,71.0,78.0,62.0,38.0,88.0,82.0,70.0,86.0,34.0,34.0,32.0,13.0,5.0,7.0,11.0,6.0,€166.1M,92.666667
226,235243,M. de Ligt,18,Netherlands,82.0,91.0,Ajax,€27M,€11K,Right,2.0,4.0,2.0,RCB,3.0,"Oct 24, 2016",2021,6'2,196lbs,66+2,66+2,66+2,63+2,65+2,65+2,65+2,63+2,65+2,65+2,65+2,65+2,70+2,70+2,70+2,65+2,73+2,77+2,77+2,77+2,73+2,...,80+2,80+2,80+2,75+2,57.0,53.0,81.0,75.0,40.0,65.0,48.0,55.0,72.0,73.0,62.0,72.0,56.0,77.0,59.0,79.0,80.0,74.0,87.0,64.0,79.0,79.0,44.0,63.0,40.0,77.0,84.0,84.0,79.0,12.0,11.0,11.0,12.0,10.0,€43.2M,88.000000
229,230621,G. Donnarumma,19,Italy,82.0,93.0,Milan,€29M,€23K,Right,3.0,3.0,1.0,GK,22.0,"Jul 1, 2015",2021,6'5,198lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.0,12.0,12.0,34.0,8.0,28.0,12.0,14.0,24.0,28.0,46.0,54.0,64.0,74.0,38.0,24.0,72.0,34.0,72.0,18.0,30.0,26.0,14.0,50.0,24.0,68.0,20.0,14.0,16.0,88.0,78.0,72.0,78.0,88.0,€55.1M,89.333333
319,231677,M. Rashford,20,England,81.0,89.0,Manchester United,€27M,€110K,Right,2.0,4.0,4.0,LW,11.0,"Jul 1, 2014",2020,6'1,154lbs,79+2,79+2,79+2,80+2,80+2,80+2,80+2,80+2,78+2,78+2,78+2,79+2,72+2,72+2,72+2,79+2,63+2,59+2,59+2,59+2,63+2,...,53+2,53+2,53+2,60+2,75.0,78.0,71.0,75.0,72.0,83.0,77.0,78.0,65.0,80.0,90.0,93.0,88.0,79.0,77.0,87.0,68.0,79.0,71.0,77.0,70.0,42.0,81.0,74.0,74.0,73.0,32.0,40.0,33.0,11.0,6.0,15.0,7.0,14.0,€55.4M,86.333333
321,229906,L. Bailey,20,Jamaica,81.0,89.0,Bayer 04 Leverkusen,€26.5M,€54K,Left,1.0,4.0,4.0,LM,9.0,"Jan 31, 2017",2023,5'10,174lbs,76+2,76+2,76+2,81+2,80+2,80+2,80+2,81+2,79+2,79+2,79+2,80+2,71+2,71+2,71+2,80+2,59+2,54+2,54+2,54+2,59+2,...,46+2,46+2,46+2,55+2,77.0,75.0,57.0,75.0,75.0,86.0,77.0,73.0,66.0,82.0,94.0,90.0,86.0,80.0,84.0,79.0,86.0,76.0,59.0,77.0,58.0,21.0,80.0,77.0,71.0,75.0,45.0,27.0,18.0,12.0,13.0,6.0,15.0,14.0,€50.4M,86.333333

In [6]:
#OP로 정렬. 이상치/결측치 보정
hope.sort_values('OP', ascending = False).head(20)
pd.set_option('display.max_columns', 80)
hope

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Position,Jersey Number,Joined,Contract Valid Until,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,...,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,OP
25,231747,K. Mbappé,19,France,88.0,95.0,Paris Saint-Germain,€81M,€100K,Right,3.0,4.0,5.0,RM,10.0,"Jul 1, 2018",2022,5'10,161lbs,85+3,85+3,85+3,87+3,87+3,87+3,87+3,87+3,86+3,86+3,86+3,86+3,78+3,78+3,78+3,86+3,66+3,62+3,62+3,62+3,66+3,...,54+3,54+3,54+3,62+3,77.0,88.0,77.0,82.0,78.0,90.0,77.0,63.0,73.0,91.0,96.0,96.0,92.0,87.0,83.0,79.0,75.0,83.0,71.0,78.0,62.0,38.0,88.0,82.0,70.0,86.0,34.0,34.0,32.0,13.0,5.0,7.0,11.0,6.0,€166.1M,92.666667
226,235243,M. de Ligt,18,Netherlands,82.0,91.0,Ajax,€27M,€11K,Right,2.0,4.0,2.0,RCB,3.0,"Oct 24, 2016",2021,6'2,196lbs,66+2,66+2,66+2,63+2,65+2,65+2,65+2,63+2,65+2,65+2,65+2,65+2,70+2,70+2,70+2,65+2,73+2,77+2,77+2,77+2,73+2,...,80+2,80+2,80+2,75+2,57.0,53.0,81.0,75.0,40.0,65.0,48.0,55.0,72.0,73.0,62.0,72.0,56.0,77.0,59.0,79.0,80.0,74.0,87.0,64.0,79.0,79.0,44.0,63.0,40.0,77.0,84.0,84.0,79.0,12.0,11.0,11.0,12.0,10.0,€43.2M,88.000000
229,230621,G. Donnarumma,19,Italy,82.0,93.0,Milan,€29M,€23K,Right,3.0,3.0,1.0,GK,22.0,"Jul 1, 2015",2021,6'5,198lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.0,12.0,12.0,34.0,8.0,28.0,12.0,14.0,24.0,28.0,46.0,54.0,64.0,74.0,38.0,24.0,72.0,34.0,72.0,18.0,30.0,26.0,14.0,50.0,24.0,68.0,20.0,14.0,16.0,88.0,78.0,72.0,78.0,88.0,€55.1M,89.333333
319,231677,M. Rashford,20,England,81.0,89.0,Manchester United,€27M,€110K,Right,2.0,4.0,4.0,LW,11.0,"Jul 1, 2014",2020,6'1,154lbs,79+2,79+2,79+2,80+2,80+2,80+2,80+2,80+2,78+2,78+2,78+2,79+2,72+2,72+2,72+2,79+2,63+2,59+2,59+2,59+2,63+2,...,53+2,53+2,53+2,60+2,75.0,78.0,71.0,75.0,72.0,83.0,77.0,78.0,65.0,80.0,90.0,93.0,88.0,79.0,77.0,87.0,68.0,79.0,71.0,77.0,70.0,42.0,81.0,74.0,74.0,73.0,32.0,40.0,33.0,11.0,6.0,15.0,7.0,14.0,€55.4M,86.333333
321,229906,L. Bailey,20,Jamaica,81.0,89.0,Bayer 04 Leverkusen,€26.5M,€54K,Left,1.0,4.0,4.0,LM,9.0,"Jan 31, 2017",2023,5'10,174lbs,76+2,76+2,76+2,81+2,80+2,80+2,80+2,81+2,79+2,79+2,79+2,80+2,71+2,71+2,71+2,80+2,59+2,54+2,54+2,54+2,59+2,...,46+2,46+2,46+2,55+2,77.0,75.0,57.0,75.0,75.0,86.0,77.0,73.0,66.0,82.0,94.0,90.0,86.0,80.0,84.0,79.0,86.0,76.0,59.0,77.0,58.0,21.0,80.0,77.0,71.0,75.0,45.0,27.0,18.0,12.0,13.0,6.0,15.0,14.0,€50.4M,86.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47.0,65.0,Crewe Alexandra,€60K,€1K,Right,1.0,2.0,2.0,CM,22.0,"May 3, 2017",2019,5'9,134lbs,42+2,42+2,42+2,44+2,44+2,44+2,44+2,44+2,45+2,45+2,45+2,44+2,45+2,45+2,45+2,44+2,44+2,45+2,45+2,45+2,44+2,...,45+2,45+2,45+2,45+2,34.0,38.0,40.0,49.0,25.0,42.0,30.0,34.0,45.0,43.0,54.0,57.0,60.0,49.0,76.0,43.0,55.0,40.0,47.0,38.0,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K,59.000000
18203,243165,N. Christoffersson,19,Sweden,47.0,63.0,Trelleborgs FF,€60K,€1K,Right,1.0,2.0,2.0,ST,21.0,"Mar 19, 2018",2020,6'3,170lbs,45+2,45+2,45+2,39+2,42+2,42+2,42+2,39+2,40+2,40+2,40+2,38+2,35+2,35+2,35+2,38+2,30+2,31+2,31+2,31+2,30+2,...,32+2,32+2,32+2,29+2,23.0,52.0,52.0,43.0,36.0,39.0,32.0,20.0,25.0,40.0,41.0,39.0,38.0,40.0,52.0,41.0,47.0,43.0,67.0,42.0,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K,57.666667
18204,241638,B. Worman,16,England,47.0,67.0,Cambridge United,€60K,€1K,Right,1.0,3.0,2.0,ST,33.0,"Jul 1, 2017",2021,5'8,148lbs,45+2,45+2,45+2,45+2,46+2,46+2,46+2,45+2,44+2,44+2,44+2,44+2,38+2,38+2,38+2,44+2,34+2,30+2,30+2,30+2,34+2,...,28+2,28+2,28+2,33+2,25.0,40.0,46.0,38.0,38.0,45.0,38.0,27.0,28.0,44.0,70.0,69.0,50.0,47.0,58.0,45.0,60.0,55.0,32.0,45.0,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K,60.333333
18205,246268,D. Walker-Rice,17,England,47.0,66.0,Tranmere Rovers,€60K,€1K,Right,1.0,3.0,2.0,RW,34.0,"Apr 24, 2018",2019,5'10,154lbs,47+2,47+2,47+2,47+2,46+2,46+2,46+2,47+2,45+2,45+2,45+2,46+2,39+2,39+2,39+2,46+2,36+2,32+2,32+2,32+2,36+2,...,31+2,31+2,31+2,35+2,44.0,50.0,39.0,42.0,40.0,51.0,34.0,32.0,32.0,52.0,61.0,60.0,52.0,21.0,71.0,64.0,42.0,40.0,48.0,34.0,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K,59.666667
18206,246269,G. Nugent,16,England,46.0,66.0,Tranmere Rovers,€60K,€1K,Right,1.0,3.0,2.0,CM,33.0,"Oct 30, 2018",2019,5'10,176lbs,43+2,43+2,43+2,45+2,44+2,44+2,44+2,45+2,45+2,45+2,45+2,46+2,45+2,45+2,45+2,46+2,46+2,46+2,46+2,46+2,46+2,...,47+2,47+2,47+2,46+2,41.0,34.0,46.0,48.0,30.0,43.0,40.0,34.0,44.0,51.0,57.0,55.0,55.0,51.0,63.0,43.0,62.0,47.0,60.0,32.0,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K,59.333333

In [7]:
# 나이가 19살임에도 Overall이 150인것을 확인하였으면, 어떻게 처리할지 생각해 봅시다.
pd.set_option('display.max_columns', 80)
hope[hope['Overall']>100]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Position,Jersey Number,Joined,Contract Valid Until,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,...,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,OP
11422,237160,R. Williams,19,England,150.0,79.0,Manchester United,€875K,€8K,Right,1.0,3.0,2.0,CB,52.0,"Jan 1, 2016",2019,6'0,165lbs,46+2,46+2,46+2,47+2,46+2,46+2,46+2,47+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2,55+2,57+2,57+2,57+2,55+2,...,62+2,62+2,62+2,57+2,32.0,27.0,63.0,58.0,37.0,51.0,35.0,36.0,55.0,50.0,72.0,74.0,58.0,52.0,59.0,43.0,65.0,41.0,68.0,30.0,66.0,56.0,29.0,43.0,49.0,51.0,63.0,68.0,66.0,7.0,5.0,6.0,6.0,9.0,€2.2M,102.666667

In [8]:
# 같은 포지션의 선수를 살펴보니, CB포지션의 점수가 같으면, Overall이 같은 것을 볼 수 있습니다.
hope[hope['Position'] == 'CB'][['Position', 'Overall','CB']].sort_values('Overall', ascending = False)
hope['Overall'][11422] = 75

<ipython-input-8-aee7fa473ad9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hope['Overall'][11422] = 75
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3417: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [9]:
hope.head()
hope.sort_values('OP', ascending = False)[['Name', 'Position']]

                  Name Position
11422      R. Williams       CB
25           K. Mbappé       RM
229      G. Donnarumma       GK
226         M. de Ligt      RCB
1143   Vinícius Júnior       LW
...                ...      ...
18163         Wang Xin      RWB
18161     P. Wieliczko       CM
18132       Liu Yaoxin       CM
18176       T. Hillman       RM
18184        D. Horton       CM

[3327 rows x 2 columns]

In [10]:
#포지션별로 묶어주기
gk_list = ['GK']
cb_list = ['CB', 'LCB', 'RCB', 'RB', 'LB']
mf_list = ['RCM', 'LCM', 'RDM', 'CDM', 'CM','RM', 'CAM']
st_list = ['ST', 'LW', 'RW']

In [11]:
#OP 기준으로 내림차순 정렬(각 포지션별로 OP기준 3명씩 뽑아야함)
hope = hope.sort_values(by = ['Position','OP'],ascending = False)

#각 포지션별 3명씩으로 제한
st_count = 3
mf_count = 3
cb_count = 3
gk_count = 3

#뽑힌 유망주 ID기준으로 리스트 만들기
hope_gk_id = []
hope_cb_id = []
hope_mf_id = []
hope_st_id = []

#반복문으로 유망주 뽑기
for index in hope.index :
    if hope['Position'][index] in gk_list :
        if gk_count != 0:
            hope_gk_id.append(hope['ID'][index])
            gk_count -= 1
    elif hope['Position'][index] in cb_list :
        if cb_count != 0:
            hope['Position'][index] = 'CB'
            hope_cb_id.append(hope['ID'][index])
            cb_count -= 1
    elif hope['Position'][index] in mf_list :
        if mf_count != 0:
            hope['Position'][index] = 'MF'
            hope_mf_id.append(hope['ID'][index])
            mf_count -= 1
    elif hope['Position'][index] in st_list:
        if st_count != 0:
            hope['Position'][index] = 'ST'
            hope_st_id.append(hope['ID'][index])
            st_count -=1

<ipython-input-11-85d1f511dda1>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hope['Position'][index] = 'ST'
<ipython-input-11-85d1f511dda1>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hope['Position'][index] = 'MF'
<ipython-input-11-85d1f511dda1>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hope['Position'][index] = 'CB'

In [12]:
#각 3명 뽑혔는지 확인
hope_mf_id

[231747, 233049, 227796]

In [13]:
#isin 함수 이용하여 뽑힌 선수 데이터 불러오기
hope_gk = hope[hope['ID'].isin(hope_gk_id)]
hope_cb = hope[hope['ID'].isin(hope_cb_id)]
hope_mf = hope[hope['ID'].isin(hope_mf_id)]
hope_st = hope[hope['ID'].isin(hope_st_id)]

In [14]:
hope_gk = hope_gk[['Name', 'Age', 'Nationality', 'Overall', 'Potential','OP', 'Position', 'Club', 'Value']]
hope_gk

,Name,Age,Nationality,Overall,Potential,OP,Position,Club,Value
229,G. Donnarumma,19,Italy,82.0,93.0,89.333333,GK,Milan,€29M
734,A. Lafont,19,France,78.0,90.0,86.000000,GK,Fiorentina,€14M
1544,A. Lunin,19,Ukraine,76.0,88.0,84.000000,GK,CD Leganés,€10.5M

In [15]:
hope_cb = hope_cb[['Name', 'Age', 'Nationality', 'Overall', 'Potential','OP', 'Position', 'Club', 'Value']]
hope_cb

,Name,Age,Nationality,Overall,Potential,OP,Position,Club,Value
226,M. de Ligt,18,Netherlands,82.0,91.0,88.000000,CB,Ajax,€27M
2784,J. Koundé,19,France,73.0,86.0,81.666667,CB,FC Girondins de Bordeaux,€6.5M
2292,I. Konaté,19,France,74.0,84.0,80.666667,CB,RB Leipzig,€7.5M

In [16]:
hope_mf = hope_mf[['Name', 'Age', 'Nationality', 'Overall', 'Potential','OP', 'Position', 'Club', 'Value']]
hope_mf

,Name,Age,Nationality,Overall,Potential,OP,Position,Club,Value
25,K. Mbappé,19,France,88.0,95.0,92.666667,MF,Paris Saint-Germain,€81M
1004,J. Sancho,18,England,77.0,89.0,85.000000,MF,Borussia Dortmund,€14.5M
570,C. Pulisic,19,United States,79.0,87.0,84.333333,MF,Borussia Dortmund,€18M

In [17]:
hope_st = hope_st[['Name', 'Age', 'Nationality', 'Overall', 'Potential','OP', 'Position', 'Club', 'Value']]
hope_st

,Name,Age,Nationality,Overall,Potential,OP,Position,Club,Value
561,L. Martínez,20,Argentina,79.0,86.0,83.666667,ST,Inter,€18M
1327,K. Dolberg,20,Denmark,76.0,85.0,82.000000,ST,Ajax,€12M
3418,M. Kean,18,Italy,72.0,87.0,82.000000,ST,Juventus,€6.5M

In [18]:
hope_e = pd.concat([hope_gk, hope_cb, hope_mf, hope_st])

In [19]:
hope_e

,Name,Age,Nationality,Overall,Potential,OP,Position,Club,Value
229,G. Donnarumma,19,Italy,82.0,93.0,89.333333,GK,Milan,€29M
734,A. Lafont,19,France,78.0,90.0,86.000000,GK,Fiorentina,€14M
1544,A. Lunin,19,Ukraine,76.0,88.0,84.000000,GK,CD Leganés,€10.5M
226,M. de Ligt,18,Netherlands,82.0,91.0,88.000000,CB,Ajax,€27M
2784,J. Koundé,19,France,73.0,86.0,81.666667,CB,FC Girondins de Bordeaux,€6.5M
2292,I. Konaté,19,France,74.0,84.0,80.666667,CB,RB Leipzig,€7.5M
25,K. Mbappé,19,France,88.0,95.0,92.666667,MF,Paris Saint-Germain,€81M
1004,J. Sancho,18,England,77.0,89.0,85.000000,MF,Borussia Dortmund,€14.5M
570,C. Pulisic,19,United States,79.0,87.0,84.333333,MF,Borussia Dortmund,€18M
561,L. Martínez,20,Argentina,79.0,86.0,83.666667,ST,Inter,€18M
1327,K. Dolberg,20,Denmark,76.0,85.0,82.000000,ST,Ajax,€12M
3418,M. Kean,18,Italy,72.0,87.0,82.000000,ST,Juventus,€6.5M